version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/frontend-new/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/frontend-new/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
