spring:
  datasource:
    url: jdbc:postgresql://hangar_new_db:5432/hangar
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"

fake-user:
  enabled: false

hangar:
  dev: false
  base-url: "https://hangar.benndorf.dev"
  plugin-upload-dir: "/hangar/uploads"

  announcements:
    -
      text: "This is a staging server for testing purposes. Data could be deleted at any time. email confirmations are disabled. If you wanna help test, sneak into #hangar-dev"
      color: "#ff544b"

  sso:
    auth-url: "https://hangar-auth.benndorf.dev"
    oauth-url: "https://hangar-auth.benndorf.dev/hydra"
    client-id: "${SSO_CLIENT_ID}"

  security:
    api:
      url: "https://hangar-auth.benndorf.dev"
      avatar-url: "https://hangar-auth.benndorf.dev/avatar/%s?size=120x120"
    token-secret: "${TOKEN_SECRET}"

logging:
  level:
    root: INFO
    org.springframework: INFO
