spring:
  datasource:
    url: jdbc:postgresql://hangar_new_db:5432/hangar
    username: hangar
    password: hangar
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat

fake-user:
  enabled: false

hangar:
  dev: false
  auth-url: "https://hangar-auth.benndorf.dev"
  base-url: "https://hangar.benndorf.dev"
  plugin-upload-dir: "/hangar/uploads"

  announcements:
    -
      text: "This is a staging server for testing purposes. Data could be deleted at any time. email confirmations are disabled. If you wanna help test, sneak into #hangar-dev"
      color: "#ff544b"

  sso:
    secret: "changeme"
    api-key: "changeme"

  security:
    api:
      url: "https://hangar-new.benndorf.dev"
      avatar-url: "https://hangar-auth.benndorf.dev/avatar/%s?size=120x120"

  projects:
    name-regex: "^[a-zA-Z0-9-_]{3,}$"
